// src/components/CodeBlock.js
// Renders a code snippet generated by TEACH (see backend teachBrain.js's
// "code" response field) in a monospace block. Previously this field was
// generated and simply discarded by the frontend.
import React from 'react';

export default function CodeBlock({ code }) {
  if (!code) return null;

  return (
    <div style={S.wrap}>
      <div className="small text-faint" style={S.label}>CODE</div>
      <pre style={S.pre}><code style={S.code}>{code}</code></pre>
    </div>
  );
}

const S = {
  wrap: { marginTop: 'var(--space-3)' },
  label: { fontWeight: 700, letterSpacing: 1, marginBottom: 6 },
  pre: {
    margin: 0, padding: 'var(--space-4)', borderRadius: 10, overflowX: 'auto',
    background: '#1E1300', border: '1px solid var(--color-border)'
  },
  code: { fontFamily: "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace", fontSize: 13.5, lineHeight: 1.6, color: '#F5EFE3', whiteSpace: 'pre' }
};
