// src/components/Mermaid.js
// Renders a mermaid diagram string generated by TEACH (see backend
// teachBrain.js's "mermaid" response field) into an inline SVG. Previously
// this field was generated and simply discarded by the frontend — it's
// first-class teaching content (logic flow diagrams), same as `code`.
import React, { useEffect, useRef, useState, useId } from 'react';
import mermaid from 'mermaid';
import { useTheme } from '../context/ThemeContext';

let initializedForTheme = null;

export default function Mermaid({ chart }) {
  const containerRef = useRef(null);
  const [error, setError] = useState(null);
  const { theme } = useTheme();
  const id = `mermaid-${useId().replace(/:/g, '')}`;

  useEffect(() => {
    if (!chart) return;
    let cancelled = false;

    // mermaid.initialize() is global config, not per-render — only re-run it
    // when the theme actually changes, to avoid redundant reinitialization
    // on every message.
    const mermaidTheme = theme === 'dark' ? 'dark' : 'default';
    if (initializedForTheme !== mermaidTheme) {
      mermaid.initialize({ startOnLoad: false, theme: mermaidTheme, securityLevel: 'strict' });
      initializedForTheme = mermaidTheme;
    }

    mermaid.render(id, chart)
      .then(({ svg }) => {
        if (!cancelled && containerRef.current) {
          containerRef.current.innerHTML = svg;
          setError(null);
        }
      })
      .catch(err => {
        if (!cancelled) setError(err.message || 'Diagram failed to render');
      });

    return () => { cancelled = true; };
  }, [chart, theme, id]);

  if (!chart) return null;

  return (
    <div style={S.wrap}>
      <div className="small text-faint" style={S.label}>DIAGRAM</div>
      {error ? (
        <div className="small text-muted">Diagram could not be rendered.</div>
      ) : (
        <div ref={containerRef} style={S.diagram} />
      )}
    </div>
  );
}

const S = {
  wrap: { marginTop: 'var(--space-3)', padding: 'var(--space-3)', background: 'var(--color-bg)', border: '1px solid var(--color-border)', borderRadius: 10 },
  label: { fontWeight: 700, letterSpacing: 1, marginBottom: 6 },
  diagram: { overflowX: 'auto', display: 'flex', justifyContent: 'center' }
};
